### ISSUE TITLE
List all of the permissions

### ISSUE THREAD

**Issue by ricardo777** [eneadm/ladder#10]
Thank you for the package. I have tested and read the documentation. But how can we list all of the permissions available?

With that we can make a user edit page with the permissions to add or remove the user permission.

Thanks

**Comment by eneadm** [comment]
Hello @ricardo777, retrieving the permissions can be done via the HasRoles trait as described in the documentation with the $user->permissions() method. Unfortunately though this package is strictly created for immutable role permissions. Most applications though do not implement user editable permission since it can break core logic leading to unpredictable behaviour. This package intentionally blocks the possibility of permission mutation and leaves that to the developer's hand so when new features are added only he/she should determine what role gets what permission. Obviously there are exceptions on this theory but if your use case is different than there are many packages out there that can provide such DB editable permission options 😊

**Comment by ricardo777** [comment]
Hello Eneadm, yes after looking more thoroughly between this package and the Spatie permissions, I can see the differences of choices. This issue can be closed. Thank you for the information.
