### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by amansaini419** [eneadm/ladder#2]
Hello,

Can anyone provide live example of how to use this repo?

**Comment by eneadm** [comment]
Hello @amansaini419,

This package very simple to install and get started. Once you have your (new or existing) laravel setup, you just follow the instructions provided in the [readme.md](https://github.com/eneadm/ladder#readme)

Run:
```shell
composer require eneadm/ladder
php artisan ladder:install
php artisan migrate
```

In your `App\Models\User` model add the `HasRoles` trait like so:
```php
use Ladder\HasRoles;
 
class User extends Authenticatable
{
    use HasRoles;
}
```

Finally manage your roles and permissions in `App\Providers\LadderServiceProvider`, here you can create whatever roles and permissions you'd like to have. A good example would be:

```php
Ladder::role('admin', 'Administrator', ['*'])->description('Some description for the admin role.');

Ladder::role('accountant', 'Accountant', [
    'invoice:read',
    'invoice:create',
    'invoice:update', // Update status to paid for example...
])->description('Some description for the accountant role.');

Ladder::role('customer', 'Customer', [
    'invoice:read',
    'invoice:create',
])->description('Some description for the customer role.');
```

And you are done, you have Roles and Permissions in your laravel app setup. These links might also help you developing your app further:

- How to assign roles to users, **Assign Roles:** [link](https://github.com/eneadm/ladder#assign-roles)
- Understanding laravel policies: [link](https://laravel.com/docs/10.x/authorization#writing-policies)
- How to implement policies with ladder, **Authorization**: [link](https://github.com/eneadm/ladder#authorization)

Let me know if this was helpful friend :-)

**Comment by amansaini419** [comment]
So, it means every time I have to implement certain task, I need to check the permission before the implementation.

**Comment by eneadm** [comment]
Yes and no, depending if you want to add some policy check for that specific feature. There are many reasons why we create roles and permissions in our apps but basically it comes down to these: 

- Guarding specific endpoints/features to be accessible only for users with the correct permissions. Otherwise return 401 Unauthorized.
- Providing the authenticated users permissions to the frontend so it can determine what features to enable/disable.

Keep in mind that not every endpoint or feature requires a permission, some may be available to all roles. In those cases you don't need to create a permission & policy.

**Comment by eneadm** [comment]
I believe all questions have been answered here so I am going to close this issue.
